eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.202.136:9999/eureka/
server:
  port: 8002
spring:
  application:
    name: service-producer
  zipkin:
    base-url: http://192.168.202.136:9900