eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.202.136:9999/eureka/
server:
  port: 6000
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
          username: 
          password: 
      label: master
      